import { PropTypes } from 'react'

export const EditorMapProps = {
  subEntity: PropTypes.number,
  activeEntityId: PropTypes.number,
  activeComponent: PropTypes.string,
  subComponent: PropTypes.string,
  currentPattern: PropTypes.object,
  stops: PropTypes.array,
  editSettings: PropTypes.object,
  mapState: PropTypes.object,
  feedSource: PropTypes.object,
  feedInfo: PropTypes.object,
  zoomToTarget: PropTypes.string,
  entities: PropTypes.array,
  activeEntity: PropTypes.object,
  entityEdited: PropTypes.bool,
  offset: PropTypes.number,
  tripPatterns: PropTypes.array,
  updateActiveEntity: PropTypes.func,
  saveActiveEntity: PropTypes.func,
  setActiveEntity: PropTypes.func,
  newGtfsEntity: PropTypes.func,
  fetchTripPatterns: PropTypes.func,
  updateMapSetting: PropTypes.func,
  removeControlPoint: PropTypes.func,
  updateUserMetadata: PropTypes.func,
  user: PropTypes.object,
  sidebarExpanded: PropTypes.bool,
  hidden: PropTypes.bool,
  drawStops: PropTypes.bool // whether to draw stops or not (based on zoom level)
}
